### ISSUE TITLE
view profile user

### ISSUE THREAD

**Issue by Ghadeer93** [FACG2/Student-Help#10]
- [x] Make view "HTML " (1H)

- [x] Show dilates  from  database  "User table" (3H)

- [x] style "Css" (2H)

- [x] Testing "may be"  (2H)
