### ISSUE TITLE
Project skeleton

### ISSUE THREAD

**Issue by mahmne** [FACG2/Student-Help#12]
- [x] folder structure #14

- [x] DB  setup #15 
- [x] database  schema 
 
- [x] set up express server
- [x] pre-commit  and linter 
 

- [x] initialise heroku project 

- [x] setup  travis
