### ISSUE TITLE
Sign Up 

### ISSUE THREAD

**Issue by Ghadeer93** [FACG2/Student-Help#2]
- [x] create sign up view "html components" and route (1h)

- [x] taking user details and store in database " Users table " (4h)

- [x] hash password (1h)

- [x] redirect to landing page "Return user into home page  " (1H)

- [x] make style "Css" (3H)

- [x] tests (1H)
