### ISSUE TITLE
Log in 

### ISSUE THREAD

**Issue by Ghadeer93** [FACG2/Student-Help#3]
- [x] take email from user , make check on Database (4H)

- [x] check password user whit hashed password which store in Database (2H)

- [x] redirect into home page (1H)

- [x] style "Css" (1H)

- [x] testing (3h)
