### ISSUE TITLE
Add New Book

### ISSUE THREAD

**Issue by Ghadeer93** [FACG2/Student-Help#4]
- [x] Make view "html component"  , Add book click "redirect new page" (1H)

- [x] Take dilates from user and store in database "Make check before store" (3H)

- [x]  Redirect to view page "view books which add by user" (2H)

- [x] Style "Css" (2H)

- [x] Testing (2H)
