### ISSUE TITLE
Show all books for same user

### ISSUE THREAD

**Issue by Ghadeer93** [FACG2/Student-Help#5]
- [x] Make view "Html " and Css (2H)

- [x] Add delete button for each books (2H)

- [x] Add new button in same page (1h)

- [x] Testing (1H)
